# Generated by Django 3.0.7 on 2020-06-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uplod_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
