# Generated by Django 3.0.7 on 2020-06-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_common'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceUplode',
            new_name='Service_Assign',
        ),
        migrations.RenameModel(
            old_name='ServiceAssign',
            new_name='Service_Uplode',
        ),
    ]
