# Generated by Django 3.0.7 on 2020-06-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_auto_20200623_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Common',
        ),
    ]
