# Generated by Django 3.0.7 on 2020-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_auto_20200624_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
    ]
