# Generated by Django 3.0.7 on 2020-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, default='vendor', max_length=100, null=True),
        ),
    ]
