# Generated by Django 3.0.7 on 2020-06-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0009_auto_20200624_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='PtoV',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='modelapp.Vendor'),
            preserve_default=False,
        ),
    ]
