# Generated by Django 3.0.7 on 2020-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0010_products_ptov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, default='hyd', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, default=9066371333, max_length=100, null=True),
        ),
    ]
