# Generated by Django 3.0.7 on 2020-06-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0011_auto_20200624_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='name_of_product',
        ),
    ]
