# Generated by Django 3.0.7 on 2020-06-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0014_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUplode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ManyToManyField(blank=True, to='modelapp.Products'),
        ),
    ]
